Header
Konfeta3-33/Weekend pull request #32
Opened 2021-03-19 10:04 UTC by ToxicEKB

2021-03-19 10:46 UTC, Konfeta3-33 requested changes
Антон, привет! Небольшие комментарии.

2021-03-19 10:46 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +          <div style={{height}} id={accessibilityIds.button} className="blob">
А где стили этого класса прописаны?

2021-03-19 10:46 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +        </div>
Мы уже настроили роуты, поэтому ссылки лучше делать через Link to

2021-03-19 10:46 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +                    </li>
тут аналогично

2021-03-23 11:52 UTC, ToxicEKB commented on src/components/header/Header.js
> +          <div style={{height}} id={accessibilityIds.button} className="blob">
Так, скорее всего он вообще лишний, выводится на всякий случай, так и остался висеть

2021-03-25 13:40 UTC, merged