Header coding
Konfeta3-33/Weekend pull request #52
Opened 2021-03-26 18:07 UTC by boburazimov

2021-03-27 09:39 UTC, Konfeta3-33 requested changes
Бобур, привет!
Все хорошо, небольшие комментарии

2021-03-27 09:39 UTC, Konfeta3-33 commented on src/components/header/Header.css
> +    position: relative;
Бобур, привет!
В тейлвинде это просто класс relative

2021-03-27 09:39 UTC, Konfeta3-33 commented on src/components/header/Header.css
> +    padding: 10px 20px;
А это в тейлвинде рх- и ру-

2021-03-27 09:39 UTC, Konfeta3-33 commented on src/components/header/Header.css
> +    position: absolute;
Это absolute

2021-03-27 09:39 UTC, Konfeta3-33 commented on src/components/header/Header.css
> +    top: 10px;
А это так и будет top и right

2021-03-27 16:28 UTC, Konfeta3-33 requested changes

2021-03-27 16:28 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +                          <a href={`/categories/${item.id}`}>{item.name}</a>
Бобур, т.к. у нас роты уже настроены то вместо а тут должно быть Link to - как и везде

2021-03-27 16:28 UTC, Konfeta3-33 commented on src/components/SubCategories/SubCategories.js
> +    <div className="px-4 mb-4 mt-5 max-w-sm mx-auto flex justify-between">
лучше делать margin-bottom своему элементу, т.е. header-у, а не у сабКатегорий делать margin-top

2021-03-27 21:36 UTC, Konfeta3-33 requested changes

2021-03-27 21:36 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +      inputRef.current.focus();
Бобур, у  inputa вроде должно быть сво-во autoFocus, посмотри, пожалуйста, чтобы ref не использовать.

2021-03-27 21:36 UTC, Konfeta3-33 commented on src/components/header/Header.js
> +    history.push(`/search/?name=${searchValue}`);
У нас нет такой страницы, страницы результата поиска.

2021-03-27 21:36 UTC, Konfeta3-33 commented on src/helpers/requests.js
> +export const searchByName = (name) => getData(`${baseUrl}/api/services/?name=${name}`);
Чтобы этот запрос выполнился, его надо позвать; как раз со страницы результата поиска...Надо будет задать вопрос про эту страницу менеджерам/дизайнерам.

2021-03-28 12:49 UTC, boburazimov commented on src/helpers/requests.js
> +export const searchByName = (name) => getData(`${baseUrl}/api/services/?name=${name}`);
Да, я просто пока реализовал сам запрос что бы проверить сервер, все работает.

2021-03-28 12:50 UTC, boburazimov commented on src/components/header/Header.js
> +    history.push(`/search/?name=${searchValue}`);
ок, закомментировал.

2021-03-28 12:53 UTC, boburazimov commented on src/components/header/Header.js
> +      inputRef.current.focus();
прописал autoFocus, но думаю место ref придется использовать useEffect.

2021-03-28 16:08 UTC, Konfeta3-33 commented on src/helpers/requests.js
> +export const searchByName = (name) => getData(`${baseUrl}/api/services/?name=${name}`);
ок

2021-03-28 22:10 UTC, Konfeta3-33 approved these changes

2021-03-28 22:10 UTC, merged