Create SearchPage.js - request
Konfeta3-33/Weekend pull request #67
Opened 2021-03-30 15:34 UTC by boburazimov

2021-03-30 22:46 UTC, Konfeta3-33 requested changes

2021-03-30 22:46 UTC, Konfeta3-33 commented on src/pages/SearchPage.js
> +  const {status, data: categories} = useQuery(
Бобур, все верно, только тут надо наверно не  categories получать, а services

2021-03-30 22:46 UTC, Konfeta3-33 commented on src/pages/SearchPage.js
> +        {status === "success" && (<SubCategories subCategories={categories}/>)}
Если success, тогда надо рендерить не SubCategories, а CategoryItem

2021-03-30 22:46 UTC, Konfeta3-33 commented on src/pages/SearchPage.js
> +export default SearchPage;
Не забывай про крайнюю пустую строку :)

2021-03-31 22:22 UTC, Konfeta3-33 requested changes

2021-03-31 22:22 UTC, Konfeta3-33 commented on src/pages/SearchPage.js
> +            <CategoryItem key={idx} item={item}/>
Бобур, а ты проверял эту страницу? Проверял в принципе как поиск отрабатывает? он действительно выводит эти айтемы? Дальше в этот айтем можно провалится и попасть в сервис?

2021-04-01 04:20 UTC, boburazimov commented on src/pages/SearchPage.js
> +            <CategoryItem key={idx} item={item}/>
проверял страницу, отрисовка происходить айтомов, по нажатию на отрисованный айтом нет действий, так как я пока не знаю всю логику, и пока еще нет верстки, так же нет в макетах.

2021-04-01 17:53 UTC, Konfeta3-33 requested changes

2021-04-01 17:53 UTC, Konfeta3-33 commented on src/pages/SearchPage.js
> +const SearchPage = ({toggleFavorites, favorites}) => {
Бобур, проверь этот момент. Айтемы кликабельны? Сердечки кликабельны?

2021-04-02 09:42 UTC, Konfeta3-33 approved these changes

2021-04-02 09:43 UTC, merged