Добавила удаление из избранного
Konfeta3-33/Weekend pull request #71
Opened 2021-03-31 21:15 UTC by EvgeniyaKa

2021-03-31 22:20 UTC, Konfeta3-33 requested changes

2021-03-31 22:20 UTC, Konfeta3-33 commented on src/components/Favorites/Favorites.js
> +const Favorites = ({toggleFavorites, favorites}) => {
Женя, тут надо без деструктуризации принимать пропсом функцию и массив, тогда все заработает

2021-03-31 22:20 UTC, Konfeta3-33 commented on src/components/Favorites/Favorites.js
> +             {(!favorites || favorites.length < 1) &&
Женя, а зачем тут второе условие?

2021-03-31 22:20 UTC, Konfeta3-33 commented on src/components/Favorites/FavoritesItem.js
> +const FavoritesItem = ({ item: { name, image, id }, redirectToService, toggleFavorites}) => {
Женя, а зачем тогда нужен этот компонент?

2021-04-01 10:49 UTC, EvgeniyaKa commented on src/components/Favorites/Favorites.js
> +             {(!favorites || favorites.length < 1) &&
раньше в куки ничего не было, я сейчас даже если в избранное ничего не добавить приходит пустой массив.

2021-04-01 11:20 UTC, merged